### ISSUE TITLE
Именование

### ISSUE THREAD

**Issue by kinda-neat** [EvgeniyChuprov/sliderPlugin#4]
Очень общий момент конечно) но давай посмотрим на один из примеров, вот интерфейс через который можно "потыкать" слайдер
![image](https://user-images.githubusercontent.com/27883524/64949099-a79e9400-d8a2-11e9-96f4-a65abec442ca.png)
Как понимать что такое min/max и отличать его от value min/value max? вот я смотрю и понимаю что min/max - это границы в которых будет хендл перемещаться, а что за value min/max еще? переименуй конкретнее, если что можем здесь обсудить

еще походу дела буду дописывать

**Comment by kinda-neat** [comment]
Several переводится как несколько, у тебя жестко захардкожено в рамках приложения что их может быть только два, поэтому стоит написать ближе к этому, можно как-нибудь типа Two handles - в интерфейсе, а внутри называть типа isDouble, мб ты лучше предложишь

**Comment by EvgeniyChuprov** [comment]
Переименовал  value min/max.
Еще такие варианты есть, если больше подойдут.
lower value - higher value
slider - second slider
stick position  - position second stick

**Comment by Sergio-Ka** [comment]
Здесь же до кучи:
1. именование классов css типа range-slider__value-min_vertical, range-slider__tool-min и подобные.
2. классы css к которым идет обращение и работа из скриптов именуются с префиксом js-, при этом на эти классы стили не навешиваются, они используются только для скриптов, таким образом даже если скрипты не будут использоваться, а классы с префиксом уберутся, вид не изменится, потому как стили висят на основном классе, который полностью дублирует класс с префиксом js- (точнее класс с префиксом дублирует название основного класса).
3. именование классов js всегда с большой буквы, sliderCreate именован с маленькой.
4. именование методов класса Observer не совсем соотвествует тому, что выполняется в методах. Переименовать лучше примерно так subscribe => addSubscriber, unsubscribe => removeSubscriber, publish => notifySubscribers
5. именовать схожие сущности одинаково, так как возникает путаница. Например:
const upright = this.options.vertical;
слева upright справа vertical. Пусть бы и было везде vertical как boolean - есть значит вертикально, нет (false) значит горизонтально. Подобные вещи не только здесь посмотри во всем проекте.
6. _calculateMovingCoordinatesByClick(newTop, length) {
Тут в двойне плохо. Во-первых newTop плохо, так как ты тащишь знание о внешнем виде (либо верхушка либо лево) в модель. А в абстрактной модели не должно быть знания о том как она отображаться будет, в ней есть только знания (в данном конкретном случае) о минимальном значении, максимальном значении, значение слайдера, наличие или отсуствие второго слайдера и если есть, то его значение. Ориентация может хранится в модели, но только как поле со значением статичное, в котором берется инфа. А когда ты говоришь новыйВерх, то получается что у тебя вертикальная ориентация. Тут может быть position скажем поле должно быть.
Во-вторых byClick тоже плохо, потому что знание о внешнем мире, что не должно быть у модели. У нее есть только интерфейс в который приходят новые координаты, а как они поменялись по клику или перетаскиванием  - модели все равно. Тут возможно стоит сделать один метод. Если они не объединяются легко, значит возможно реализованы не совсем удачно и не совсем продумано какая информация должна приходить, чтобы это делалось относительно просто в модели.
7. Именование методов   _changeInput() и _changeOutput не отображает сути методов. Первый метод у тебя по сути вешает обработчики на элементы DOM, а второй - записывает в инпуты пришедшую из плагина информацию.
