### ISSUE TITLE
Названия jquery элементов

### ISSUE THREAD

**Issue by kinda-neat** [EvgeniyChuprov/sliderPlugin#5]
Чекни везде что у тебя соблюдена конвенция по именованию элементов, с которыми можно работать как с jquery-объектами
У нас в даже стандартах это есть (4-й пункт) https://github.com/fullstack-development/front-end-best-practices/blob/master/JS/jQuery.md

**Comment by Sergio-Ka** [comment]
isDouble у тебя тоже в панели должен начинаться со знака $
