### ISSUE TITLE
this.each в файле плагина

### ISSUE THREAD

**Issue by Sergio-Ka** [EvgeniyChuprov/sliderPlugin#8]
return this.each(() => {
        this.controller.subscribe(this.model.processEvent.bind(this.model));
        this.controller.subscribe(this.view.processEvent.bind(this.view));
        this.model.addSubscriber(this.controller.processEvent.bind(this.controller));
        this.view.subscribe(this.controller.processEvent.bind(this.controller));

        this.controller.init();

        this.data('setting', this.model.options);
      });
Здесь это не имеет смысла на мой взгляд. Посмотреть и убрать.

**Comment by EvgeniyChuprov** [comment]
Убрал до того как увидел issue
