### ISSUE TITLE
нарушение разделения ответственности и инкапсуляции

### ISSUE THREAD

**Issue by Sergio-Ka** [EvgeniyChuprov/sliderPlugin#9]
_showSettingMajorHandleValue() {
    const visibilityMajorHandle = this.options.severalHandles ? 'block' : 'none';
    this.majorHandleValue.css('display', visibilityMajorHandle);
    this.sliderText.css('display', visibilityMajorHandle);
  }

Данный метод находится в классе панели, но определяет отображение слайдера, хотя это его ответственность. Это очень плохая практика. А если например панели не будет, а слайдер будет использоваться по прямому назначению? Тут нужно явно передавать параметр в плагин, какой-нибудь isDoubled и уже по нему внутри смотреть отрисовывать второй ползунок или нет и как в зависимости от этого будет выглядеть модель.

**Comment by EvgeniyChuprov** [comment]
Этот метод относится к отображению настроек плагина, сам плагин он не затрагивает. 
Показывает значение одного или ползунков.
![image](https://user-images.githubusercontent.com/36810364/65037159-bdb95c80-d955-11e9-895a-f6fa7d5790c4.png)
![image](https://user-images.githubusercontent.com/36810364/65037123-abd7b980-d955-11e9-9213-801056642eab.png)

**Comment by kinda-neat** [comment]
вот здесь тоже не затрагивает this.sliderText.css('display', visibilityMajorHandle);?
